version: "3.9"

services:
  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"  # наружу 8000 для API Gateway
    env_file:
      - ./api_gateway/.env
    depends_on:
      - service_users
      - service_orders

  service_users:
    build: ./service_users
    container_name: service_users
    ports:
      - "8001:8000"  # наружу 8001, внутри контейнера 8000
    env_file:
      - ./service_users/.env

  service_orders:
    build: ./service_orders
    container_name: service_orders
    ports:
      - "8002:8000"  # наружу 8002, внутри контейнера 8000
    env_file:
      - ./service_orders/.env
